apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-demo-v1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AzimulAyaz/canary-demo-azimul.git
    targetRevision: feature-canary-v2  # <--- Branch name yahan dalo
    path: k8s/overlays/canary          # <--- Path bhi badal do
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-space
  syncPolicy:
    automated:
      prune: true
      selfHeal: true